include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    sized_box_for_whitespace: ignore
    avoid_print: ignore
    deprecated_member_use: ignore
    use_build_context_synchronously: ignore
