name: blockchain_university_voting_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.3
  firebase_app_check: ^0.3.2+4
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.4
  firebase_storage: ^12.4.4
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^19.0.0
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  flutter_phoenix: ^1.1.1
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  go_router: ^14.6.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  local_auth: ^2.3.0
  logger: ^2.5.0
  mailer: ^6.4.1
  provider: ^6.1.2
  reown_appkit: ^1.3.0
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/contracts/
    - assets/images/
    - .env
