// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSelUUKuQiWYnt0RzLdXSr0slMzBvKtPw',
    appId: '1:971972876725:web:cd296aeb332cd01c1a21fc',
    messagingSenderId: '971972876725',
    projectId: 'blockchain-voting-system-f1dfe',
    authDomain: 'blockchain-voting-system-f1dfe.firebaseapp.com',
    storageBucket: 'blockchain-voting-system-f1dfe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbaTNdL6_BTU__GYQusGLHrMB0SIWm-58',
    appId: '1:971972876725:android:0699d851cb645d641a21fc',
    messagingSenderId: '971972876725',
    projectId: 'blockchain-voting-system-f1dfe',
    storageBucket: 'blockchain-voting-system-f1dfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-EsD_EzN5SiDDxqt80m4xLGNX7qt9Fi0',
    appId: '1:971972876725:ios:0702fc64aca0aff51a21fc',
    messagingSenderId: '971972876725',
    projectId: 'blockchain-voting-system-f1dfe',
    storageBucket: 'blockchain-voting-system-f1dfe.firebasestorage.app',
    iosBundleId: 'com.example.blockchainUniversityVotingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-EsD_EzN5SiDDxqt80m4xLGNX7qt9Fi0',
    appId: '1:971972876725:ios:0702fc64aca0aff51a21fc',
    messagingSenderId: '971972876725',
    projectId: 'blockchain-voting-system-f1dfe',
    storageBucket: 'blockchain-voting-system-f1dfe.firebasestorage.app',
    iosBundleId: 'com.example.blockchainUniversityVotingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSelUUKuQiWYnt0RzLdXSr0slMzBvKtPw',
    appId: '1:971972876725:web:372accf250f60bf41a21fc',
    messagingSenderId: '971972876725',
    projectId: 'blockchain-voting-system-f1dfe',
    authDomain: 'blockchain-voting-system-f1dfe.firebaseapp.com',
    storageBucket: 'blockchain-voting-system-f1dfe.firebasestorage.app',
  );

}